/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author romaf
 */
public class PesanBus extends javax.swing.JFrame {

    /**
     * Creates new form DataBus
     */
    public PesanBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AsalBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TujuanBox = new javax.swing.JComboBox<>();
        WaktuBox = new javax.swing.JComboBox<>();
        NextButton = new javax.swing.JButton();
        HPField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KTPField = new javax.swing.JTextField();
        NamaField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        KetField = new javax.swing.JTextField();

        jTextField1.setText("No.Hp   :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data Bus  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 90, 17);

        AsalBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asal", "Banda Aceh", "Medan", "Padang" }));
        AsalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsalBoxActionPerformed(evt);
            }
        });
        jPanel1.add(AsalBox);
        AsalBox.setBounds(20, 180, 110, 22);

        jLabel2.setText("Keterangan Penjemputan :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 220, 150, 16);

        TujuanBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tujuan", "Banda Aceh", "Medan", "Padang" }));
        jPanel1.add(TujuanBox);
        TujuanBox.setBounds(20, 360, 110, 22);

        WaktuBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waktu", "08:00", "12:00", "20:00", " " }));
        jPanel1.add(WaktuBox);
        WaktuBox.setBounds(20, 400, 72, 22);

        NextButton.setText("Next ");
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextButtonMouseClicked(evt);
            }
        });
        jPanel1.add(NextButton);
        NextButton.setBounds(290, 470, 70, 22);
        jPanel1.add(HPField);
        HPField.setBounds(80, 140, 160, 22);

        jLabel5.setText("No HP :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 60, 20);

        jLabel3.setText("No KTP :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 100, 60, 20);
        jPanel1.add(KTPField);
        KTPField.setBounds(80, 100, 160, 20);

        NamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NamaField);
        NamaField.setBounds(80, 60, 160, 22);

        jLabel6.setText("Nama :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 60, 60, 20);

        BackButton.setText("Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(50, 470, 72, 22);
        jPanel1.add(KetField);
        KetField.setBounds(20, 240, 300, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsalBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsalBoxActionPerformed

    private void NamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
    Menu menu = new Menu();
    menu.setVisible(true);
    dispose();
    }//GEN-LAST:event_BackButtonMouseClicked

    private void NextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonMouseClicked
    StrukBus struk = new StrukBus();
    struk.setVisible(true);
    dispose();
    }//GEN-LAST:event_NextButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AsalBox;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField HPField;
    private javax.swing.JTextField KTPField;
    private javax.swing.JTextField KetField;
    private javax.swing.JTextField NamaField;
    private javax.swing.JButton NextButton;
    private javax.swing.JComboBox<String> TujuanBox;
    private javax.swing.JComboBox<String> WaktuBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
